#!/usr/bin/env php
<?php
/** Require shop bootstrap file to use path constants */
require_once dirname(dirname(dirname(__DIR__))) . DIRECTORY_SEPARATOR .
             'source' . DIRECTORY_SEPARATOR .
             'bootstrap.php';

require_once VENDOR_PATH .
             'oxid-esales' . DIRECTORY_SEPARATOR .
             'eshop-virtual-namespace-generator' . DIRECTORY_SEPARATOR .
             'src' . DIRECTORY_SEPARATOR .
             'VirtualClassMapGenerator.php';

$generator = new VirtualClassMapGenerator();
$generator->generateAll();
