#!/usr/bin/env php
<?php

$projectRoot = dirname(dirname(dirname(dirname(__FILE__))));
$vendorDirectory = $projectRoot . '/vendor';
require_once $vendorDirectory . '/autoload.php';
if (!defined('OX_BASE_PATH')) {
    define('OX_BASE_PATH', $projectRoot . '/source');
}
require_once $projectRoot . '/source/oxfunctions.php';
require_once $vendorDirectory. '/oxid-esales/eshop-virtual-namespace-generator/src/VirtualClassMapGenerator.php';

$generator = new VirtualClassMapGenerator();
$generator->generateAll();
